name: Convert Base64 Content

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Get base64 content from URL
        env:
          URL: <https://vahid.sajed-the-nerd5501.workers.dev/sub>
        run: |
          curl -sL $URL | jq -r '.content' | base64 --decode > OUTPUT.txt

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add OUTPUT.txt
          git commit -m "Update OUTPUT.txt"
          git push
